---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    attributes: 
      aws :
        access_key_id : <%= ENV['AWS_ACCESS_KEY'] %>
        secret_access_key : <%= ENV['AWS_SECRET_KEY'] %> 
      nginx :
        geoip :
          country_dat_url : https://s3-us-west-1.amazonaws.com/neon-dependencies/GeoIP.dat.gz
          city_dat_url : https://s3-us-west-1.amazonaws.com/neon-dependencies/GeoLiteCity.dat.gz
      opsworks :
        instance : 
          private_ip : "10.0.0.1"
          availability_zone : "us-east-1d"
          region : "us-east"
        layers : 
          tracklog_collector :
            instances : 
              log-collector1 : 
                private_ip : "10.0.2.2"
                availability_zone : "us-east-1d"
                region : "us-east"
              
              log-collector2 : 
                private_ip : "10.0.3.2"
                availability_zone : "us-east-1c"
                region : "us-east"
          log-collector : 
            instances : 
              log-collector1 : 
                private_ip : "10.0.0.2"
                availability_zone : "us-east-1d"
                region : "us-east"
              
              log-collector2 : 
                private_ip : "10.0.1.2"
                availability_zone : "us-east-1c"
                region : "us-east"

suites:
  - name: trackserver_deploy
    run_list:
      - recipe[trackserver::default]
    attributes: 
      deploy :
        "track_server" :
          document_root : "trackserver"
          scm :
            scm_type : "git"
            repository : "git@github.com:neon-lab/neon-codebase.git"
            revision : "working"
      opsworks :
        activity : "setup"

  - name: isp_deploy
    run_list:
      - recipe[neonisp::default]
    attributes: 
      deploy :
        "image_serving_platform" :
          document_root : "neonisp"
          scm :
            scm_type : "git"
            repository : "git@github.com:neon-lab/neon-codebase.git"
            revision : "working"      
      opsworks :
        activity : "setup"

  - name: statsmanager_deploy
    run_list:
      - recipe[stats_manager::default]
    attributes: 
      deploy :
        "stats_manager" :
          document_root : "statsmanager"
          scm :
            scm_type : "git"
            repository : "git@github.com:neon-lab/neon-codebase.git"
            revision : "statsmanager_service"      
      opsworks :
        activity : "setup"

  - name: mastermind_deploy
    run_list:
      - recipe[mastermind::default]
    attributes: 
      deploy :
        "mastermind" :
          document_root : "mastermind"
          scm :
            scm_type : "git"
            repository : "git@github.com:neon-lab/neon-codebase.git"
            revision : "working"      
      opsworks :
        activity : "setup"

  - name: opencv
    run_list:
      - recipe[neon-opencv::default]
    attributes:

  - name: dev_setup
    run_list:
      - recipe[neon::full_py_repo]
    attributes:
      neon:
        code_revision: "working"
        
      